pull_request_rules:
  - name: impersonation-test
    conditions:
      - "#approved-reviews-by >= 0"
    actions:
      comment:
        message: "impersonation probe"
        bot_account: eliezeryomtov-dotcom


